version: "3"
services: 
    core:
        image: umrds/serval_core_worker
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /lib/modules:/lib/modules
            - ./dotcore:/root/.core
        tty: true
        privileged: true
        cap_add:
            - NET_ADMIN
        environment:
          - CORE_PARAMS=
          - DISPLAY